In [18]:
import numpy as np
import pandas as pd

In [2]:
# NumPy's main datatypes is ndarray - n dimensional array
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
a2 = np.array([[1, 2.0, 3.3],
             [4, 5, 6.5]])
a3 = np.array([[[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]],
            [[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]]])

In [4]:
a1

array([1, 2, 3])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

### Dot Product

In [7]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5, 3))
mat2 = np.random.randint(10, size=(5, 3))

mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [8]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [9]:
mat1.shape, mat2.shape

((5, 3), (5, 3))

In [10]:
mat1 * mat2 # element wise multiplication

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [ ]:
# dot product 
np.dot(mat1, mat2)

In [11]:
# transpose mat1
mat1.T

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]])

In [12]:
mat2.shape, mat1.T.shape # now is matching

((5, 3), (3, 5))

In [13]:
mat1.shape, mat2.T.shape

((5, 3), (3, 5))

In [14]:
mat3 = np.dot(mat1, mat2.T)
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [15]:
mat3.shape

(5, 5)

## Dot product example (nut butter sales)

In [16]:
np.random.seed(0)
# number of jars sold
sales_amounts = np.random.randint(20, size=(5, 3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [19]:
# create weekly_sales DataFrame
weekly_sales = pd.DataFrame(sales_amounts, 
                            index=["Mon", "Tues", "Wed", "Thurs", "Fri"],
                           columns=["Almond butter", "Peanut butter", "Cashew butter"])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [20]:
# create prices array
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [21]:
# create butter_prices Dataframe - error
butter_prices= pd.DataFrame(prices, index=["Price"], 
                           columns=["Almond butter", "Peanut butter", "Cashew butter"])
butter_prices

ValueError: Shape of passed values is (3, 1), indices imply (1, 3)

In [22]:
prices.shape

(3,)

 what pandas is expecting is three columns and one row
 but this is three rows, one column
 we want to reshape this to be one three

In [23]:
# create butter_prices Dataframe - error
butter_prices= pd.DataFrame(prices.reshape(1, 3), index=["Price"], 
                           columns=["Almond butter", "Peanut butter", "Cashew butter"])
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [25]:
sales_amounts.sahpe

AttributeError: 'numpy.ndarray' object has no attribute 'sahpe'

In [26]:
 total_sales = prices.dot(sales_amounts)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

 shape aren't aligned, let's transpose

In [27]:
total_sales = prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

 create daily_sales

create the same thing as here, but within a panda's data frame so we can kind of just add the two data frame together

In [31]:
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [30]:
# if we flip weekly frame, wich is our data frame, flip that, transpose that
# and then dot product of those two, because then if we flip these two right 

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [33]:
weekly_sales.T.shape

(3, 5)

In [34]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tues  Wed  Thurs  Fri
Price  240   138  458    232  142

In [40]:
 # new column
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total ($)
Mon               12             15              0        240
Tues               3              3              7        138
Wed                9             19             18        458
Thurs              4              6             12        232
Fri                1              6              7        142

In [38]:
type(daily_sales)

pandas.core.frame.DataFrame

### Comparison Operators

In [44]:
a1, a2

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]))

In [41]:
 a1 > a2 # each element in a1 is greater than each element in a2

array([[False, False, False],
       [False, False, False]])

In [45]:
bool_array = a1 >= a2
bool_array

array([[ True,  True, False],
       [False, False, False]])

In [46]:
type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))

In [48]:
a1 > 5, a1 <5, a1 == a2

(array([False, False, False]),
 array([ True,  True,  True]),
 array([[ True,  True, False],
        [False, False, False]]))

## Sorting Arrays

In [49]:
random_array = np.random.randint(10, size=(3, 5))
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [50]:
np.sort(random_array)

array([[1, 5, 7, 8, 9],
       [0, 3, 4, 8, 9],
       [0, 2, 3, 3, 5]])

In [52]:
np.argsort(random_array) # sort the indexes

array([[2, 3, 0, 1, 4],
       [4, 3, 2, 0, 1],
       [2, 3, 0, 4, 1]], dtype=int64)

 sometimes you might not want to sort the values instead, we want to figure out
 which index has the highest value.

In [53]:
a1

array([1, 2, 3])

In [54]:
np.argsort(a1)

array([0, 1, 2], dtype=int64)

In [60]:
s = np.array([2, 3, 1, 4, 5])
sort_index = np.argsort(s)
print(sort_index)

[2 0 1 3 4]


In [68]:
s.sort()
print(s)

[1 2 3 4 5]


In [72]:
np.argmin(a1)

0

In [73]:
np.argmax(a1)

2

In [74]:
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [75]:
np.argmax(random_array, axis=0)

array([1, 1, 1, 0, 0], dtype=int64)

In [76]:
np.argmax(random_array, axis=1)

array([4, 1, 1], dtype=int64)

this is position four, this is the highest number, to access zero and then we go
 on position one, we have 9, and in the row three, the highest is '5'
 the first row -> '9' index 4, the second row -> '9' index 1

## Turn image into a Numpy array

In [77]:
from matplotlib.image import imread

panda = imread("images/panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [78]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [79]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [82]:
car = imread("images/car-photo.png")
print(type(car))

<class 'numpy.ndarray'>


In [83]:
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352